import {
  ActivityIcon,
  ArchiveXIcon,
  ArrowUpRightIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  CircleIcon,
  CircleUserIcon,
  CircleXIcon,
  CreditCardIcon,
  DollarSignIcon,
  FolderIcon,
  GripVerticalIcon,
  HomeIcon,
  InfoIcon,
  MenuIcon,
  MoonIcon,
  MoreHorizontalIcon,
  Package2Icon,
  PanelLeftIcon,
  SearchIcon,
  SunIcon,
  TrashIcon,
  User2Icon,
  UsersIcon,
  XIcon,
} from 'lucide-react';

export { type LucideIcon } from 'lucide-react';

export const Icons = {
  Activity: ActivityIcon,
  ArchiveX: ArchiveXIcon,
  ArrowUpRight: ArrowUpRightIcon,
  Check: CheckIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  CircleAlert: CircleAlertIcon,
  CircleCheck: CircleCheckIcon,
  CircleUser: CircleUserIcon,
  CircleX: CircleXIcon,
  CreditCard: CreditCardIcon,
  DollarSign: DollarSignIcon,
  Folder: FolderIcon,
  GripVertical: GripVerticalIcon,
  Home: HomeIcon,
  Info: InfoIcon,
  Menu: MenuIcon,
  Moon: MoonIcon,
  MoreHorizontal: MoreHorizontalIcon,
  Package2: Package2Icon,
  PanelLeft: PanelLeftIcon,
  Search: SearchIcon,
  Sun: SunIcon,
  Trash: TrashIcon,
  User2: User2Icon,
  Users: UsersIcon,
  X: XIcon,
};
